name: Progress Bar CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      
    - name: Update README.md
      run: |
        node index.js > README.md

    - name: Commit and Push Changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "bot: update README.md automatically"
        git push
